<doc docid='canadagov_1' lang='pqm' source='https://www.sac-isc.gc.ca/eng/1583781906998/1583781926813#chp4b' type='parallel' original_language='eng' translation_mode='manual'>
Kinitpahk kinuwehtahsuwakon 'ciw skicinuwok weci-woli-kcicihtuwoq ksinuhkewakon Covid-19
Public Health Agency of Canada 'totoli-kinuwi-topinomon ksinuhkewakon Covid-19.
Tehpu yut qeni-mawoluhkhotiyoq, cu-tehc kkisi-nakayutomonen tan eli-sissahak yut ksinuhkewakon: tehpu qeni-kinuwi-miwkawotiyoq.
Psiw-ote wen 'cuwi-woli-wicuhkekemit weci-skat-nemsotassonuhk ksinuhkewakon Covid-19, yut-oc ehta eli-kisi-woli-miwkawotiyoq:
Musa apasultihkeq etoli- cecalokinaqatimok;
Musa lapasultihkeq etoli-maqahawolotimok, pciliw-te tan skat wisoki-pawalqotunuhk;
Musa sokiptinentultihkeq;
Kinaq-ote nisahqonasu li-miwkawotine, psihkac-ote;
Musa ali-wikuwamkomtultihkeq, pciliw-te etoli-wikultihtit kehcikotonhoticik naka tan tehpu wen kis kesinuhkat.
Sawe-kossiptinensultine-tehna; neqhomuhtine naka ekskultine kpihtinahqemihkunuk (mus-kahk kpihtinihkunuk!) wisa-qasakhotine kahsihtonuhusutiyil woli-te eli-kisuwehkiyoq; woli-pehkihtune, ewekhotiyoq sunpekonikon naka kostikonikon, tan tehpu tama etoli-wituwekhotiyoq; musa-tehna samonosultiq ksisqihkuwak, kihtonihkuwak, kosona ktunihkuwak.
Weci-aqami-kcicihtuweq tan eleyik yut ksinuhkewakon Covid-19, totolokitomuhk canada.ca/coronavirus kosona li-mattoktihikhotiq 1-833-784-4397 (tan skat ehcuwi-apenkatasinuhk).
Government of Canada yut eli-kinuwehtahsuwik.
</doc>